////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

= Summary and Outlook

This document (Part 5 of the document series "Details of the Asset Administration Shell") defines the AASX package file format for file exchange of Administration Shells based on the Open Package Conventions.

Additional parts of the document series cover (see link:#bib10[[10\]]):

* the information meta model of the Asset Administration Shell (Part 1),
* interfaces and APIs for accessing the information of Asset Administration Shells (access, modify, query, and execute information and active functionality; Part 2),
* the payload of these APIs is based on the definitions of the information model as specified in document Part 1; the API also includes operations for downloading AASX files as specified in this document,
* data specification templates (Part 3 series),
* security aspects of the Asset Administration Shell (Part 4)

