= Part 5: Package File Format (AASX)

*Specification of the Asset Administration Shell*

====
This specification is part of the https://industrialdigitaltwin.org/en/content-hub/aasspecifications[Asset Administration Shell Specification series].
====

== Version

This is version 3.2 of the specification IDTA-01005.

Previous version: 3.1

== Notice

Copyright: Industrial Digital Twin Association e.V. (IDTA)

IDTA Document Number: IDTA-01005-3-2

DOI: **TO BE ADDED**

This work is licensed under a
https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

SPDX-License-Identifier: CC-BY-4.0

**DATE TO BE ADDED**

== How to Get in Contact

Contact: https://industrialdigitaltwin.org/en/contact[IDTA]

Sources: https://github.com/admin-shell-io/aas-specs-aasx[GitHub]

Feedback:

* https://github.com/admin-shell-io/aas-specs-aasx/issues/new/choose[new issues, bugs]

* https://github.com/admin-shell-io/questions-and-answers[Questions and Answers]

== Editorial Notes

=== History
This version, version 3.1, was produced from May 2025 on by the Workstream "Specifications of the Asset Administration Shell" of the "Open Technology" working group of the Industrial Digital Twin Association (IDTA).

Version 3.1 was finalized in May 2025 by the Workstream "Specifications of the Asset Administration Shell" of the "Open Technology" working group of the Industrial Digital Twin Association (IDTA).
It is the first published as html.

Version 3.0 of this document is the continuation of the definition of the AASX Package Exchange Format that was originally part of Part 1 of the document series "Details of the Asset Administration Shell".
Part 1 was split after V3.0RC02.
Part 5 (this document) now focuses on the file exchange format AASX.

This document was produced from September 2022 to January 2023 by the sub working group "Asset Administration Shell" of the joint working group of the Plattform Industrie 4.0 working group "Reference Architectures, Standards and Norms" and the "Open Technology" working group of the Industrial Digital Twin Association (IDTA).
It is the first version published by the IDTA.

include::./shared/IDTA-01xxx_Versioning.adoc[]

include::./shared/IDTA-01xxx_Conformance.adoc[]
